- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: "remove dependencies no longer needed"
  apt:
    autoremove: yes

- name: "install nodejs, npm"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    apt-get install -y nodejs
    npm install -g n
    n 13.8.0
    node -v
    npm -v

- name: install PM2
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest
    #version: 3.5.2


