- name: copy artifact to EC2 server
  become: true
  copy:
    src: artifact.tar.gz
    dest: .
    backup: yes

- name: "Extract Artifact"
  become: true
  shell: |
    tar -xvzf artifact.tar.gz -C .

- name: "start app"
  become: true
  shell: |
    npm install
    sudo pm2 start npm -- start