- name: copy artifact to EC2 server
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz
    backup: yes

- name: "Extract Artifact"
  shell: |
    cd ~
    tar -xvzf artifact.tar.gz -C .

- name: "start app "
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start